server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: BookingApp-Api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vriddhi
    username: postgres
    password: password

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
